# Generated by Django 4.2.25 on 2025-10-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='row_count',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
