# Generated by Django 4.2.25 on 2025-10-13 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generator', '0002_schema_row_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
